### ISSUE TITLE
error occurred when set stride as 2

### ISSUE THREAD

**Issue by taicaile** [developer0hye/Simple-PyTorch-Deformable-Convolution-v2#4]
Hello, thanks for your repo.

There is a problem when set stride to 2.

Can you figure out what the problem is? ( I cannot solve it...)

**Comment by developer0hye** [comment]
Can you upload your error?

**Comment by taicaile** [comment]
Hello,
Here is the output:
```bash
Traceback (most recent call last):
  File "dcn.py", line 66, in <module>
    out = model(fake_in)
  File "/home/li/miniconda3/envs/pytorchcpu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "dcn.py", line 52, in forward
    x = torchvision.ops.deform_conv2d(input=x, 
  File "/home/li/miniconda3/envs/pytorchcpu/lib/python3.8/site-packages/torchvision/ops/deform_conv.py", line 89, in deform_conv2d
    return torch.ops.torchvision.deform_conv2d(
RuntimeError: offset output dims: (122, 122) - computed output dims: (244, 244)
```

You can replicate it by add the following in `dcn.py`:

```python
if __name__ == "__main__":

    model = DeformableConv2d(3,64,3,2)
    fake_in = torch.randn(1,3,244,244)
    out = model(fake_in)
    print(out.shape)
```

**Comment by developer0hye** [comment]
@taicaile 
I fixed this issue. Pull the latest version code and check it!

**Comment by taicaile** [comment]
> @taicaile
> I fixed this issue. Pull the latest version code and check it!

Hello, I already tested it, work well now.

Thanks for your quick response.
